name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        sudo apt install postgresql
        pip install poetry
        poetry export --without-hashes -f requirements.txt --output ./requirements.txt
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python devops_demo/manage.py runserver 0.0.0.0:8000
        python devops_demo/manage.py test
